name: CI/CD Pipeline

on:
  push:
    branches:
      - master # Change to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test
      run: |
        # Replace these commands with your build and test scripts
        echo "Building and testing your application..."

    - name: Deploy to Jenkins
      uses: appleboy/jenkins-action@v2
      with:
        url: http://34.238.42.131/
        user: diksha
        token: 11f3cc906e54baf657f7750bf546f59975
        job: jenkins-git
